import React, { FC, useContext } from "react";
import Head from 'next/head';
import { Topbar, NavbarComponent, Footer } from "../ui";

import styles from './Layout.module.css';
import { LayoutContext } from "../../context/layout";

interface Props {
    children: React.ReactNode,
    title: string
}

export const Layout: FC<Props> = ({ children, title }) => {

    const { isHome } = useContext( LayoutContext );
    return (
        <div style={{ overflowX: 'hidden' }}>
            <Head>
                <title>{ title }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar/>
            <NavbarComponent/>
            <main className={ !isHome ? styles.content : styles['general-content'] }>
                { children }
            </main>
            <Footer/>
        </div>
    )
}