import React, { FC, useContext, useState, useEffect } from 'react';
import Head from 'next/head';
import { Topbar, NavbarComponent, Footer } from '../ui';

import styles from './Layout.module.css';
import { LayoutContext } from '../../context/layout';

interface Props {
    children: React.ReactNode,
    title: string
}

export const Layout: FC<Props> = ({ children, title }) => {

    const [layoutClassName, setLayoutClassName] = useState('');
    const { isHome, isData, isAboutUs } = useContext( LayoutContext );
    useEffect(() => {
        if( isHome ) setLayoutClassName( styles.home );
        else if ( isData ) setLayoutClassName( styles.data );
        else if ( isAboutUs ) setLayoutClassName( styles['about-us'] )
    }, [])
    
    
    return (
        <div style={{ overflow: 'hidden' }}>
            <Head>
                <title>{ title }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Topbar/>
            <NavbarComponent/>
            <main className={ layoutClassName }>
                { children }
            </main>
            <Footer/>
        </div>
    )
}

